apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:fb69aa89f4f6087959ccd35247691fc28d8bf448
        ports:
        - containerPort: 80
