apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 203171087948.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:86b41847d3105bb5ccda4e163b8da8538b3391a6
        ports:
        - containerPort: 80
