apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/google-store-electronics:b762c4f543046c503bd27ce65064cf4887022c0f
        ports:
        - containerPort: 80
