apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlepay:8a2da9f9960fa204f75991a192a985c4560c657c
        ports:
        - containerPort: 80
