apiVersion: v1
kind: Service
metadata:
  name: googlepay-service
  labels:
    app: googlepay
spec:
  type: ClusterIP
  selector:
    app: googlepay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
