apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlegrocery:fb69aa89f4f6087959ccd35247691fc28d8bf448
        ports:
        - containerPort: 80
